# Site settings
title: Willis Club
email: luke@willis.club
description: > # this means to ignore newlines until "baseurl:"
  Home to the Willis family. Purveyors of entrepreneurial endeavors.
  Elisabet is the author of the Evermemory series.
  Luke is a Software Consultant--currently employed by Pariveda Solutions.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://willis.club" # the base hostname & protocol for your site
twitter_username: lukemwillis
github_username: lukemwillis

# Build settings
markdown: kramdown
exclude: [.bundle, bin, vendor]
